src/Entity/Basket.php
<?php

namespace App\Entity;

use App\Repository\BasketRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=BasketRepository::class)
 */
class Basket extends Base
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="baskets")
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity=Product::class, inversedBy="baskets")
     */
    private $product;

    /**
     * @ORM\Column(type="integer")
     */
    private $piece;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getProduct(): ?Product
    {
        return $this->product;
    }

    public function setProduct(?Product $product): self
    {
        $this->product = $product;

        return $this;
    }

    public function getPiece(): ?int
    {
        return $this->piece;
    }

    public function setPiece(int $piece): self
    {
        $this->piece = $piece;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User extends Base implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\NotBlank(message="Bu alan boş bırakılamaz")
     * @Assert\Email(message="Lütfen geçerli bir e-posta adresi girin")
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = ["ROLE_USER"];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @var string
     * @ORM\Column(type="string")
     * @Assert\NotBlank(message="Bu alan Boş bırakılamaz")
     * @Assert\Length(min="3",minMessage="En az {{ limit }} karakter giriniz")
     */
    private $name;

    /**
     * @var string
     * @ORM\Column(type="string")
     * @Assert\NotBlank(message="Bu alan boş bırakılamaz")
     * @Assert\Length(min="3",minMessage="En az {{ limit }} karakter giriniz")
     */
    private $surname;

    /**
     * @ORM\OneToMany(targetEntity=Basket::class, mappedBy="user")
     */
    private $baskets;

    /**
     * @ORM\OneToMany(targetEntity=Order::class, mappedBy="user")
     */
    private $orders;

    /**
     * @ORM\OneToMany(targetEntity=UserAddress::class, mappedBy="user")
     */
    private $userAddresses;

    public function __construct()
    {
        $this->baskets = new ArrayCollection();
        $this->orders = new ArrayCollection();
        $this->userAddresses = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string)$this->email;
    }

    public function getRoles(): ?array
    {
        return $this->roles;
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSurname(): ?string
    {
        return $this->surname;
    }

    public function setSurname(string $surname): self
    {
        $this->surname = $surname;

        return $this;
    }

    public function getFullName()
    {
        return $this->name . ' ' . $this->surname;
    }

    /**
     * @return Collection|Basket[]
     */
    public function getBaskets(): Collection
    {
        return $this->baskets;
    }

    public function addBasket(Basket $basket): self
    {
        if (!$this->baskets->contains($basket)) {
            $this->baskets[] = $basket;
            $basket->setUser($this);
        }

        return $this;
    }

    public function removeBasket(Basket $basket): self
    {
        if ($this->baskets->contains($basket)) {
            $this->baskets->removeElement($basket);
            // set the owning side to null (unless already changed)
            if ($basket->getUser() === $this) {
                $basket->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Order[]
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    public function addOrder(Order $order): self
    {
        if (!$this->orders->contains($order)) {
            $this->orders[] = $order;
            $order->setUser($this);
        }

        return $this;
    }

    public function removeOrder(Order $order): self
    {
        if ($this->orders->contains($order)) {
            $this->orders->removeElement($order);
            // set the owning side to null (unless already changed)
            if ($order->getUser() === $this) {
                $order->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|UserAddress[]
     */
    public function getUserAddresses(): Collection
    {
        return $this->userAddresses;
    }

    public function addUserAddress(UserAddress $userAddress): self
    {
        if (!$this->userAddresses->contains($userAddress)) {
            $this->userAddresses[] = $userAddress;
            $userAddress->setUser($this);
        }

        return $this;
    }

    public function removeUserAddress(UserAddress $userAddress): self
    {
        if ($this->userAddresses->contains($userAddress)) {
            $this->userAddresses->removeElement($userAddress);
            // set the owning side to null (unless already changed)
            if ($userAddress->getUser() === $this) {
                $userAddress->setUser(null);
            }
        }

        return $this;
    }
}

src/Controller/Web/Basket/BasketController.php
<?php


namespace App\Controller\Web\Basket;


use App\Controller\Web\WebBaseController;
use App\Entity\Basket;
use App\Entity\Product;
use App\Repository\BasketRepository;
use Exception;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class BasketController
 * @package App\Controller\Web\Basket
 * @Route("/basket")
 * @IsGranted("IS_AUTHENTICATED_FULLY")
 */
class BasketController extends WebBaseController
{

    /**
     * @Route("/add",name="web_add_basket")
     * @param Request $request
     * @param BasketRepository $basketRepository
     * @return JsonResponse
     */
    public function new(Request $request, BasketRepository $basketRepository): JsonResponse
    {
        try {
            if ($request->request->getInt('piece') < 1)
                throw new Exception('En az 1 ürün eklemelisiniz');

            if (!$user = $this->getUser())
                throw new Exception('Lütfen önce giriş yapınız');

            $em = $this->getDoctrine()->getManager();

            if (!$product = $em->getRepository(Product::class)->findOneBy(['id' => $request->request->getInt('product_id'), 'status' => true]))
                throw new Exception('Böyle bir ürün bulunmuyor');

            if ($basket = $basketRepository->findOneBy(['user' => $user, 'product' => $product]))
                $basketRepository->basketPieceUpdate($basket->getId(), $basket->getPiece() + $request->request->getInt('piece'));
            else
                $basketRepository->basketCreate($user, $product, $request->request->all());

            return $this->json([
                'status' => true,
                'message' => 'Ürün Sepete Eklendi',
                'basket_count' => $basketRepository->basketPieceTotal($user)
            ]);

        } catch (Exception $e) {

            return $this->json([
                'status' => false,
                'message' => $e->getPrevious() ? $e->getPrevious()->getMessage() : $e->getMessage()
            ]);
        }
    }

    /**
     * @Route("/piece-update",name="web_basket_piece_update")
     * @param Request $request
     * @param BasketRepository $basketRepository
     * @return JsonResponse
     */
    public function basketPieceUpdate(Request $request, BasketRepository $basketRepository): JsonResponse
    {
        try {
            if ($request->request->getInt('piece') < 1)
                throw new Exception('En az 1 ürün eklemelisiniz');

            $em = $this->getDoctrine()->getManager();

            if (!$product = $em->getRepository(Product::class)->findOneBy(['id' => $request->request->getInt('product_id'), 'status' => true]))
                throw new Exception('Böyle bir ürün bulunmuyor');

            if ($basket = $basketRepository->findOneBy(['user' => $this->getUser(), 'product' => $product]))
                $basketRepository->basketPieceUpdate($basket->getId(), $request->request->getInt('piece'));

            return $this->json([
                'status' => true,
                'message' => 'Ürün Adeti Güncellendi',
            ]);

        } catch (Exception $e) {

            return $this->json([
                'status' => false,
                'message' => $e->getPrevious() ? $e->getPrevious()->getMessage() : $e->getMessage()
            ]);
        }
    }

    /**
     * @Route("/basket-piece-total",name="web_basket_piece_total")
     * @param BasketRepository $basketRepository
     * @return RedirectResponse|Response
     */
    public function basketPieceTotal(BasketRepository $basketRepository): Response
    {
        if (!$user = $this->getUser())
            return $this->redirectToRoute('app_login');

        return $this->render('web/basket/basket_button.html.twig', [
            'basket_count' => $basketRepository->basketPieceTotal($user)
        ]);
    }

    /**
     * @Route("/show",name="web_basket_show")
     */
    public function show(): Response
    {
        $baskets = $this->getDoctrine()->getRepository(Basket::class)->findBy(['user' => $this->getUser()]);
        return $this->render('web/basket/show.html.twig', [
            'baskets' => $baskets
        ]);
    }

    /**
     * @Route("/delete",name="web_basket_delete")
     * @param Request $request
     * @param BasketRepository $basketRepository
     * @return JsonResponse
     */
    public function delete(Request $request, BasketRepository $basketRepository): JsonResponse
    {
        try {

            $em = $this->getDoctrine()->getManager();

            if (!$basket = $em->getRepository(Basket::class)->find($request->request->getInt('basket_id')))
                throw new Exception('Böyle bir ürün bulunmuyor');

            $em->remove($basket);
            $em->flush();

            return $this->json([
                'status' => true,
                'message' => 'Ürün Silindi',
            ]);

        } catch (Exception $e) {

            return $this->json([
                'status' => false,
                'message' => $e->getPrevious() ? $e->getPrevious()->getMessage() : $e->getMessage()
            ]);
        }
    }

}

templates/web/basket/basket_button.html.twig
<a href="{{ path('web_basket_show') }}" class="btn btn-info mr-2">
    Sepetim <span class="badge badge-light" id="basketItemPiece">{{ basket_count|default(0) }}</span>
</a>

templates/web/basket/show.html.twig
{% extends 'web/layout/base.html.twig' %}

{% block title %}{{ 'Sepetim' }}{% endblock %}

{% block body %}
    {% if baskets %}
        <div class="row">
            <div class="col-md-9">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>Ürün</th>
                            <th>Adet</th>
                            <th>Toplam</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        {% set total = 0 %}
                        {% for basket in baskets %}
                            {% set total = total + basket.product.price * basket.piece %}
                            <tr>
                                <td>
                                    <a href="{{ path('web_product_show',{'slug':basket.product.slug}) }}" target="_blank" class="text-dark">{{ basket.product.name }}</a>
                                </td>
                                <td style="width: 150px">
                                    <form class="m-0" id="addBasketForm" method="post">
                                        <input type="hidden" name="product_id" value="{{ basket.product.id }}">
                                        <input type="number" id="piece" name="piece" class="form-control" max="{{ basket.product.stock }}" step="1" min="1" value="{{ basket.piece }}">
                                    </form>
                                </td>
                                <td>{{ (basket.product.price * basket.piece)|number_format(2,',','.') }} {{ currency_unit() }}</td>
                                <td>
                                    <button type="button" class="btn btn-sm btn-danger basket_delete" data-id="{{ basket.id }}">Sil</button>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="col-md-3">
                <div class="d-flex justify-content-around flex-column h-100">
                    <div>
                        <h5>Toplam</h5>
                        <h4 class="text-danger">{{ total|number_format(2,',','.') }} {{ currency_unit() }}</h4>
                    </div>
                    <a href="{{ path('web_order_checkout') }}" class="btn btn-success btn-block">Siparişi Ver</a>
                </div>
            </div>
        </div>
    {% else %}
        <div class="row">
            <div class="col-md-12">
                <div class="alert alert-warning m-0">{{ app.user.fullName }}, sepetin şu an boş. Doldurmaya ne <a href="{{ path('web_home') }}">dersin</a>.</div>
            </div>
        </div>
    {% endif %}

{% endblock %}

{% block javascripts %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw=="
            crossorigin="anonymous"></script>
    <script type="text/javascript">
        const urls = {
            updatePiece: "{{ path('web_basket_piece_update') }}",
            deleteBasket: "{{ path('web_basket_delete') }}",
        };

        $(document).ready(function () {

            const basketItemPiece = $('#basketItemPiece');
            const addBasketForm = $('#addBasketForm');
            const deleteButton = $('.basket_delete');
            const piece = $('#piece');

            deleteButton.on('click', function () {
                let button = $(this);
                $.ajax({
                    type: 'POST',
                    url: urls.deleteBasket,
                    data: {basket_id: button.data('id')},
                    success: function (data) {
                        if (!data.status) return toastr.error(data.message);
                        toastr.success(data.message);
                        setTimeout(() => location.reload(), 1000)
                    },
                })
            });


            piece.on('change', function () {
                $.ajax({
                    type: 'POST',
                    url: urls.updatePiece,
                    data: addBasketForm.serialize(),
                    success: function (data) {
                        if (!data.status) return toastr.error(data.message);
                        toastr.success(data.message);
                        setTimeout(() => location.reload(), 1000)
                    },
                })
            });

        });
    </script>
{% endblock %}