src/Entity/Order.php
<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=OrderRepository::class)
 * @ORM\Table(name="`order`")
 */
class Order extends Base
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="orders")
     */
    private $user;

    /**
     * @ORM\Column(type="boolean",nullable=true)
     */
    private $status;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $order_no;

    /**
     * @ORM\ManyToOne(targetEntity=UserAddress::class, inversedBy="orders")
     */
    private $address;

    /**
     * @ORM\OneToMany(targetEntity=OrderProduct::class, mappedBy="order")
     */
    private $orderProducts;

    /**
     * @ORM\Column(type="string", length=255,columnDefinition="ENUM('pay_at_the_door')")
     */
    private $payment_type;

    public function __construct()
    {
        $this->orderProducts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStatus(): ?bool
    {
        return $this->status;
    }

    public function setStatus(bool $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getOrderNo(): ?string
    {
        return $this->order_no;
    }

    public function setOrderNo(string $order_no): self
    {
        $this->order_no = $order_no;

        return $this;
    }

    public function getPaymentType(): ?string
    {
        return $this->payment_type;
    }

    public function setPaymentType(string $payment_type): self
    {
        $this->payment_type = $payment_type;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getAddress(): ?UserAddress
    {
        return $this->address;
    }

    public function setAddress(?UserAddress $address): self
    {
        $this->address = $address;

        return $this;
    }

    /**
     * @return Collection|OrderProduct[]
     */
    public function getOrderProducts(): Collection
    {
        return $this->orderProducts;
    }

    public function addOrderProduct(OrderProduct $orderProduct): self
    {
        if (!$this->orderProducts->contains($orderProduct)) {
            $this->orderProducts[] = $orderProduct;
            $orderProduct->setOrder($this);
        }

        return $this;
    }

    public function removeOrderProduct(OrderProduct $orderProduct): self
    {
        if ($this->orderProducts->contains($orderProduct)) {
            $this->orderProducts->removeElement($orderProduct);
            // set the owning side to null (unless already changed)
            if ($orderProduct->getOrder() === $this) {
                $orderProduct->setOrder(null);
            }
        }

        return $this;
    }


}

src/Entity/UserAddress.php
<?php

namespace App\Entity;

use App\Repository\UserAddressRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=UserAddressRepository::class)
 */
class UserAddress extends Base
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="userAddresses")
     */
    private $user;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $surname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $district;

    /**
     * @ORM\Column(type="text")
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $phone;

    /**
     * @ORM\OneToMany(targetEntity=Order::class, mappedBy="address")
     */
    private $orders;

    public function __construct()
    {
        $this->orders = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSurname(): ?string
    {
        return $this->surname;
    }

    public function setSurname(string $surname): self
    {
        $this->surname = $surname;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getDistrict(): ?string
    {
        return $this->district;
    }

    public function setDistrict(string $district): self
    {
        $this->district = $district;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getAddressName(): ?string
    {
        return $this->address_name;
    }

    public function setAddressName(string $address_name): self
    {
        $this->address_name = $address_name;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    /**
     * @return Collection|Order[]
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    public function addOrder(Order $order): self
    {
        if (!$this->orders->contains($order)) {
            $this->orders[] = $order;
            $order->setAddress($this);
        }

        return $this;
    }

    public function removeOrder(Order $order): self
    {
        if ($this->orders->contains($order)) {
            $this->orders->removeElement($order);
            // set the owning side to null (unless already changed)
            if ($order->getAddress() === $this) {
                $order->setAddress(null);
            }
        }

        return $this;
    }
}

src/Controller/Admin/Order/OrderController.php
<?php


namespace App\Controller\Admin\Order;


use App\Controller\Admin\AdminBaseController;
use App\Repository\OrderRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class BasketController
 * @package App\Controller\Web\Basket
 * @Route("/order")
 */
class OrderController extends AdminBaseController
{

    /**
     * @Route("/list",name="admin_order_list")
     * @param OrderRepository $orderRepository
     * @return null |null
     */
    public function list(OrderRepository $orderRepository)
    {
        return $this->render('admin/order/list.html.twig', [
            'orders' => $orderRepository->lazyFindAll()
        ]);
    }

    /**
     * @Route("/detail/{order_no}",name="admin_order_detail")
     * @param $order_no
     * @param OrderRepository $orderRepository
     * @return null |null
     */
    public function detail($order_no, OrderRepository $orderRepository)
    {

        if (!$order = $orderRepository->findOneBy(['order_no' => $order_no])) {
            $this->addFlash('error', 'Böyle bir sipariş bulunmamaktadır.');
            return $this->redirectToRoute('admin_order_list');
        }

        return $this->render('admin/order/detail.html.twig', [
            'order' => $order
        ]);
    }

    /**
     * @Route("/approve/{order_no}",name="admin_order_approve")
     * @Route("/reject/{order_no}",name="admin_order_reject")
     * @param $order_no
     * @param Request $request
     * @param OrderRepository $orderRepository
     * @return null |null
     */
    public function orderApproveAndReject($order_no, Request $request, OrderRepository $orderRepository)
    {
        $action = $request->attributes->get('_route');

        if (!$order = $orderRepository->findOneBy(['order_no' => $order_no, 'status' => null])) {
            $this->addFlash('error', 'Böyle bir sipariş bulunamadı');
            return $this->redirectToRoute('admin_order_list');
        }

        switch ($action) {
            case 'admin_order_approve':
                $order->setStatus(true);
                foreach ($order->getOrderProducts() as $orderProduct) {
                    if ($orderProduct->getProduct()->getStock() - $orderProduct->getPiece() < 0) {
                        $this->addFlash('error', $orderProduct->getProduct()->getName() . ' isimli üründe yeterli stok yok lütfen stoklarınızı güncelleyiniz.');
                        return $this->redirectToRoute('admin_order_list');
                    } else {
                        $orderProduct->getProduct()->setStock($orderProduct->getProduct()->getStock() - $orderProduct->getPiece());
                    }
                }
                $this->addFlash('success', 'Sipariş Onaylandı');
                break;
            case 'admin_order_reject':
                $order->setStatus(false);
                $this->addFlash('error', 'Sipariş Onaylanmadı');
                break;
            default:
                $this->addFlash('error', 'Bir sorun oluştu');
                break;
        }

        $this->getDoctrine()->getManager()->flush();

        return $this->redirectToRoute('admin_order_list');

    }
}

src/Controller/Web/Order/OrderController.php
<?php


namespace App\Controller\Web\Order;


use App\Controller\Web\WebBaseController;
use App\Entity\Basket;
use App\Entity\Order;
use App\Entity\User;
use App\Entity\UserAddress;
use App\Repository\OrderProductRepository;
use App\Repository\OrderRepository;
use App\Repository\UserAddressRepository;
use Exception;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class BasketController
 * @package App\Controller\Web\Basket
 * @Route("/order")
 * @IsGranted("IS_AUTHENTICATED_FULLY")
 */
class OrderController extends WebBaseController
{
    /**
     * @Route("/checkout",name="web_order_checkout")
     * @return Response
     */
    public function index()
    {
        if (!$baskets = $this->getDoctrine()->getRepository(Basket::class)->findBy(['user' => $this->getUser()]))
            return $this->redirectToRoute('web_basket_show');

        return $this->render('web/order/index.html.twig', [
            'baskets' => $baskets
        ]);
    }

    /**
     * @Route("/new",name="web_order_new")
     * @param Request $request
     * @param UserAddressRepository $userAddressRepository
     * @param OrderProductRepository $orderProductRepository
     * @return Response
     */
    public function new(Request $request, UserAddressRepository $userAddressRepository, OrderProductRepository $orderProductRepository)
    {
        try {
            /** @var User $user */
            $user = $this->getUser();

            $em = $this->getDoctrine()->getManager();

            $address = $userAddressRepository->createAddress($user, $request->request->all());

            $order = new Order();
            $order->setUser($user);
            $order->setAddress($address);
            $order->setOrderNo(md5(uniqid()));
            $order->setPaymentType($request->request->get('payment_type'));
            $em->persist($order);

            if (!$orderProduct = $orderProductRepository->create($user->getBaskets(), $order))
                throw new Exception('Bir sorun oluştu,lütfen tekrar deneyin');

            $em->flush();

            $this->addFlash('success', 'Siparişiniz alınmıştır.');
            return $this->redirectToRoute('web_order_list');

        } catch (Exception $e) {
            $this->addFlash('error', $e->getPrevious() ? $e->getPrevious()->getMessage() : $e->getMessage());
            return $this->redirectToRoute('web_order_checkout');
        }
    }

    /**
     * @Route("/list",name="web_order_list")
     * @param OrderRepository $orderRepository
     * @return null |null
     */
    public function list(OrderRepository $orderRepository)
    {
        return $this->render('web/order/list.html.twig', [
            'orders' => $orderRepository->lazyFindAll($this->getUser())
        ]);
    }

    /**
     * @Route("/detail/{order_no}",name="web_order_detail")
     * @param $order_no
     * @param OrderRepository $orderRepository
     * @return null |null
     */
    public function detail($order_no, OrderRepository $orderRepository)
    {

        if (!$order = $orderRepository->findOneBy(['user' => $this->getUser(), 'order_no' => $order_no]))
            return $this->redirectToRoute('web_home');

        return $this->render('web/order/detail.html.twig', [
            'order' => $order
        ]);
    }
}

templates/web/order/detail.html.twig
{% extends 'web/layout/base.html.twig' %}

{% block title %}{{ 'Sipariş Detayları' }}{% endblock %}

{% block stylesheets %}
{% endblock %}

{% block body %}
    <h4 class="mb-4">{{ order.orderNo }} numaralı sipariş</h4>
    <div class="row">
        <div class="col-md-12">
            <table class="table">
                <tbody>
                <tr>
                    <th>Sipariş Numarası</th>
                    <td>{{ order.orderNo }}</td>
                </tr>
                <tr>
                    <th>Sipariş Durumu</th>
                    <td>
                        {% if order.status is null %}
                            {% set class,text = 'warning','Onay Bekliyor' %}
                        {% elseif order.status %}
                            {% set class,text = 'success','Onaylandı' %}
                        {% else %}
                            {% set class,text = 'danger','Onaylanmadı' %}
                        {% endif %}
                        <span class="badge badge-{{ class }} p-2">{{ text }}</span>
                    </td>
                </tr>
                <tr>
                    <th>Sipariş Tarihi</th>
                    <td>{{ order.createdAt ? order.createdAt|date('d.m.Y') }}</td>
                </tr>
                <tr>
                    <th>Ödeme Tipi</th>
                    <td>{{ order.paymentType == 'pay_at_the_door' ? 'Kapıda Ödeme' : 'Diğer' }}</td>
                </tr>
                <tr>
                    <th>Sipariş Adresi</th>
                    <td>
                        <table class="table">
                            <tbody>
                            <tr>
                                <th>Adı Soyadı</th>
                                <td>{{ order.address.name }} {{ order.address.surname }}</td>
                            </tr>
                            <tr>
                                <th>İl</th>
                                <td>{{ order.address.city }}</td>
                            </tr>
                            <tr>
                                <th>İlçe</th>
                                <td>{{ order.address.district }}</td>
                            </tr>
                            <tr>
                                <th>Adres</th>
                                <td>{{ order.address.address|raw }}</td>
                            </tr>
                            <tr>
                                <th>Adres Adı</th>
                                <td>{{ order.address.addressName }}</td>
                            </tr>
                            <tr>
                                <th>Telefon</th>
                                <td>{{ order.address.phone }}</td>
                            </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
                <tr>
                    <th>Ürünler</th>
                    <td>
                        <table class="table">
                            <thead>
                            <tr>
                                <th>Ürün</th>
                                <th>Adet</th>
                                <th>Toplam</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% set total = 0 %}
                            {% for orderProduct in order.orderProducts %}
                                {% set total = total + orderProduct.price %}
                                <tr>
                                    <td>
                                        <a href="{{ path('web_product_show',{'slug':orderProduct.product.slug}) }}" target="_blank" class="text-dark">{{ orderProduct.product.name }}</a>
                                    </td>
                                    <td>{{ orderProduct.piece }}</td>
                                    <td>{{ orderProduct.price|number_format(2,',','.') }} {{ currency_unit() }}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </td>
                </tr>
                <tr>
                    <th>Sipariş Tutarı</th>
                    <td>{{ total|number_format(2,',','.') }} {{ currency_unit() }}</td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

templates/web/order/index.html.twig
{% extends 'web/layout/base.html.twig' %}

{% block title %}{{ 'Sepetim' }}{% endblock %}

{% block stylesheets %}
{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-6">
            <h4>İletişim Bilgileri</h4>
            <form action="{{ path('web_order_new') }}" method="post" id="orderAddForm">
                <div class="form-group">
                    <label for="name">Ad</label>
                    <input type="text" class="form-control" id="name" name="name">
                </div>
                <div class="form-group">
                    <label for="surname">Soyad</label>
                    <input type="text" class="form-control" id="surname" name="surname">
                </div>
                <div class="form-group">
                    <label for="city">İl</label>
                    <input type="text" class="form-control" id="city" name="city">
                </div>
                <div class="form-group">
                    <label for="district">İlçe</label>
                    <input type="text" class="form-control" id="district" name="district">
                </div>
                <div class="form-group">
                    <label for="address">Adres</label>
                    <textarea name="address" id="address" cols="10" rows="5" class="form-control"></textarea>
                </div>
                <div class="form-group">
                    <label for="address_name">Adres Adı</label>
                    <input type="text" class="form-control" id="address_name" name="address_name">
                </div>
                <div class="form-group">
                    <label for="phone">Telefon</label>
                    <input type="text" class="form-control" id="phone" name="phone">
                </div>
                <h4>Ödeme Seçenekleri</h4>
                <div class="form-group form-check">
                    <input type="radio" class="form-check-input" id="pay_at_the_door" name="payment_type" value="pay_at_the_door" checked>
                    <label class="form-check-label" for="pay_at_the_door">Kapıda Ödeme</label>
                </div>
                <button type="submit" class="btn btn-success">Siparişi Tamamla</button>
            </form>
        </div>
        <div class="col-md-6">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                    <tr>
                        <th>Ürün</th>
                        <th>Adet</th>
                        <th>Toplam ({{ currency_unit() }})</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% set total = 0 %}
                    {% for basket in baskets %}
                        {% set total = total + basket.product.price * basket.piece %}
                        <tr>
                            <td><a href="{{ path('web_product_show',{'slug':basket.product.slug}) }}" target="_blank">{{ basket.product.name }}</a></td>
                            <td>{{ basket.piece }}</td>
                            <td>{{ (basket.product.price * basket.piece)|number_format(2,',','.') }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="d-flex justify-content-end">
                <div>
                    <h5>Toplam</h5>
                    <h4 class="text-danger">{{ total|number_format(2,',','.') }} {{ currency_unit() }}</h4>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/additional-methods.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/localization/messages_tr.min.js"
            integrity="sha512-rWj/F+JtHj3bknzoCOWaXAh30MHQGMfQrZXNn2Vaa28AVv1+dZQYOPT1rqCZ5soi2koqVn60aLyxN1xwXWLNxw==" crossorigin="anonymous"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $("#orderAddForm").validate({
                rules: {
                    // simple rule, converted to {required:true}
                    name: "required",
                    surname: "required",
                    city: "required",
                    district: "required",
                    address: "required",
                    address_name: "required",
                    phone: {
                        required: true,
                        phoneUS: true
                    }
                },
                submitHandler: function (form) {
                    form.submit();
                }
            });
        })
    </script>
{% endblock %}

templates/web/order/list.html.twig
{% extends 'web/layout/base.html.twig' %}

{% block title %}{{ 'Siparişlerim' }}{% endblock %}

{% block stylesheets %}
{% endblock %}

{% block body %}
    <h4 class="mb-4">Siparişlerim</h4>
    <div class="row">
        <div class="col-md-12">
            {% if orders %}
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>Sipariş Numarası</th>
                            <th>Sipariş Durumu</th>
                            <th>Sipariş Tarihi</th>
                            <th>Ödeme Tipi</th>
                            <th>Ürün Adeti</th>
                            <th>Sipariş Tutarı</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for order in orders %}
                            <tr>
                                <td>{{ order.order_no }}</td>
                                <td>
                                    {% if order.status is null %}
                                        {% set class,text = 'warning','Onay Bekliyor' %}
                                    {% elseif order.status %}
                                        {% set class,text = 'success','Onaylandı' %}
                                    {% else %}
                                        {% set class,text = 'danger','Onaylanmadı' %}
                                    {% endif %}
                                    <span class="badge badge-{{ class }} p-2">{{ text }}</span>
                                </td>
                                <td>{{ order.createdAt ? order.createdAt|date('d.m.Y') : '' }}</td>
                                <td>{{ order.payment_type == 'pay_at_the_door' ? 'Kapıda Ödeme' : 'Diğer' }}</td>
                                <td>{{ order.piece }}</td>
                                <td>{{ order.total_price|number_format(2,',','.') }} {{ currency_unit() }}</td>
                                <td><a href="{{ path('web_order_detail',{'order_no':order.order_no}) }}">Sipariş Detayı</a></td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% else %}
                <div class="alert alert-warning m-0">Siparişini bulunmamaktadır.</div>
            {% endif %}
        </div>
    </div>
{% endblock %}